name: Build Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Checkout submodules
        run: git submodule update --remote --init --recursive

      - name: Use GitHub build targets
        shell: bash
        run: |
          cp -f "${GITHUB_WORKSPACE}/BedrockLauncher/GitHub.Directory.Build.targets" "${GITHUB_WORKSPACE}/BedrockLauncher/Directory.Build.targets" 
        
      - name: Setup nuget
        uses: nuget/setup-nuget@v2

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore dependencies
        run: |
          nuget restore BedrockLauncher.sln

      - name: Build
        run: |
          msbuild "BedrockLauncher.sln" /t:Build /p:Configuration=Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: BedrockLauncher/bin/Release/net*.*-windows*.*.*.*
